
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tns.Aerolinea.Entities.AerolineaTnsModel
{

using System;
    using System.Collections.Generic;
    
public partial class Asiento
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Asiento()
    {

        this.TiquetePasajero = new HashSet<TiquetePasajero>();

    }


    public int IdAsiento { get; set; }

    public int IdAvion { get; set; }

    public short IdTipoAsiento { get; set; }

    public string Codigo { get; set; }

    public string SalidaEmergencia { get; set; }



    public virtual Avion Avion { get; set; }

    public virtual TipoAsiento TipoAsiento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TiquetePasajero> TiquetePasajero { get; set; }

}

}
