
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tns.Aerolinea.Entities.AerolineaTnsModel
{

using System;
    using System.Collections.Generic;
    
public partial class Pasajero
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pasajero()
    {

        this.TiquetePasajero = new HashSet<TiquetePasajero>();

    }


    public long IdPasajero { get; set; }

    public string Cedula { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Direccion { get; set; }

    public string Sexo { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public string Correo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TiquetePasajero> TiquetePasajero { get; set; }

}

}
