//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tns.Aerolinea.Entities.AerolineaTnsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.TiquetePasajero = new HashSet<TiquetePasajero>();
        }
    
        public long IdReserva { get; set; }
        public int IdUsuario { get; set; }
        public long IdVuelo { get; set; }
        public decimal ValorTotalReserva { get; set; }
        public System.DateTime FechaReserva { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Vuelo Vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiquetePasajero> TiquetePasajero { get; set; }
    }
}
