
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tns.Aerolinea.Entities.AerolineaTnsModel
{

using System;
    using System.Collections.Generic;
    
public partial class Tarifa
{

    public long IdVuelo { get; set; }

    public short IdTipoAsiento { get; set; }

    public decimal ValorTiquete { get; set; }



    public virtual TipoAsiento TipoAsiento { get; set; }

    public virtual Vuelo Vuelo { get; set; }

}

}
