
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tns.Aerolinea.Entities.AerolineaTnsModel
{

using System;
    using System.Collections.Generic;
    
public partial class TiquetePasajero
{

    public long IdReserva { get; set; }

    public long IdPasajero { get; set; }

    public short IdTipoAsiento { get; set; }

    public Nullable<int> IdAsiento { get; set; }

    public decimal ValorTiquete { get; set; }



    public virtual TipoAsiento TipoAsiento { get; set; }

    public virtual Asiento Asiento { get; set; }

    public virtual Pasajero Pasajero { get; set; }

    public virtual Reserva Reserva { get; set; }

}

}
