
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tns.Aerolinea.Entities.AerolineaTnsModel
{

using System;
    using System.Collections.Generic;
    
public partial class Vuelo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Vuelo()
    {

        this.Reserva = new HashSet<Reserva>();

        this.Tarifa = new HashSet<Tarifa>();

    }


    public long IdVuelo { get; set; }

    public int IdOrigen { get; set; }

    public int IdDestino { get; set; }

    public int IdAerolinea { get; set; }

    public int IdAvion { get; set; }

    public byte IdEstado { get; set; }

    public System.DateTime Fecha { get; set; }

    public System.TimeSpan Salida { get; set; }

    public string Observaciones { get; set; }



    public virtual Aerolinea Aerolinea { get; set; }

    public virtual Avion Avion { get; set; }

    public virtual Destino Destino { get; set; }

    public virtual EstadoVuelo EstadoVuelo { get; set; }

    public virtual Origen Origen { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reserva> Reserva { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tarifa> Tarifa { get; set; }

}

}
