//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tns.Aerolinea.Infrastructure.Mensajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tns.Aerolinea.Infrastructure.Mensajes.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya tiene una reserva de un vuelo para la misma fecha, no es posible generarle una nueva reserva..
        /// </summary>
        public static string ErrorReservasPrevias {
            get {
                return ResourceManager.GetString("ErrorReservasPrevias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya tiene una reserva hecha para el mismo dia. No es posible crear otra reserva..
        /// </summary>
        public static string ErrorReservaVuelo {
            get {
                return ResourceManager.GetString("ErrorReservaVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario es menor de edad y no puede realizar una reserva de vuelo..
        /// </summary>
        public static string ErrorUsuarioMenorEdad {
            get {
                return ResourceManager.GetString("ErrorUsuarioMenorEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya se encuentra registrado..
        /// </summary>
        public static string ErrorUsuarioRegistrado {
            get {
                return ResourceManager.GetString("ErrorUsuarioRegistrado", resourceCulture);
            }
        }
    }
}
