//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tns.Aerolinea.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Tns.Aerolinea.Entities.AerolineaTnsModel;
    
    public partial class AerolineaTnsEntities : DbContext
    {
        public AerolineaTnsEntities()
            : base("name=AerolineaTnsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aerolinea> Aerolinea { get; set; }
        public virtual DbSet<Avion> Avion { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Destino> Destino { get; set; }
        public virtual DbSet<EstadoVuelo> EstadoVuelo { get; set; }
        public virtual DbSet<Origen> Origen { get; set; }
        public virtual DbSet<TipoAsiento> TipoAsiento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Asiento> Asiento { get; set; }
        public virtual DbSet<Pasajero> Pasajero { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Tarifa> Tarifa { get; set; }
        public virtual DbSet<TiquetePasajero> TiquetePasajero { get; set; }
        public virtual DbSet<Vuelo> Vuelo { get; set; }
    }
}
