

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tns.Aerolinea.Data.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using Tns.Aerolinea.Entities.AerolineaTnsModel;


public partial class AerolineaTnsEntities : DbContext
{
    public AerolineaTnsEntities()
        : base("name=AerolineaTnsEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Usuario> Usuario { get; set; }

}

}

